### ISSUE TITLE
1d - Mash together beginning levels for streamlined progression

### ISSUE THREAD

**Issue by djmailhot** [RileyA/STATICly-MAD#47]

**Comment by Craig-Macomber** [comment]
To clarify for those who missed this discussion (I think it was just me and David): we want to try (perhaps for A/B testing) having fewer levels in the first overworld by merging the trivial levels into longer/more complex levels.

Intro+Discharge+FlyingEnd and Collect+Insulated+Drop would work, and reduce introduction to 2 levels instead of 6. (Thus player can first get charged in level 3, instead of 7).
